### DISCUSSION TITLE
How to collect all data from a Prometheus instance

### DISCUSSION THREAD

**Discussion by caiwenhao** [ccfos/nightingale#1229] [Q&A] [answered]
我使用kube-prometheus监控了一个k8s集群，我想把kube-prometheus的采集的数据推送到都推送到夜莺v5，在夜莺v5上做图形展示和告警。   如何让夜莺v5可以采集另一个prometheus实例的完整数据，类似联邦模式

**Comment by UlricQin** [comment, marked as answer]
两个方案：
1. 把kube-prometheus的那个prometheus作为夜莺的数据源配置到夜莺中
2. 把kube-prometheus的prometheus中配置remote write，写到n9e-server的`/prometheus/v1/write`接口

**Reply by caiwenhao** [reply]
谢谢， 通过remote write 已经成功采集到数据。 但是对象列表中没有数据， 通过Writers.WriteRelabels 把instance标签Replacement为ident，也是不行的

**Reply by 594872799** [reply]
针对1这种情况，采用thanos作为数据源去读，配置文件该怎么配呢，现在我在server.conf和webapi.conf配置了thanos-query的地址，在监控看图上报404

**Comment by caiwenhao** [comment]
```yaml
  version: 2.32.1
  remoteWrite:
  - url: "http://nightingale-nserver.n9e:80/prometheus/v1/write"
    writeRelabelConfigs:
    - sourceLabels: ["instance"]
      separator: ";"
      action: "replace"
      regex: "(.*)"
      replacement: "$1"
      targetLabel: "ident"
```
通过配置writeRelabelConfigs 解决了 对象列表无法识别
