### ISSUE TITLE
求解：各位大佬老师，在用ibex categraf-v0.2.10 做自愈脚本的时候，告警规则上设置自愈脚本不生效， 我categraf  和ibex-agent 装在一台服务器。然后夜莺的一套是用docker 装在了另外一台服务器上，求排查思路。

### ISSUE THREAD

**Issue by beginend2012** [ccfos/nightingale#1139]
### Relevant server.conf | webapi.conf

```toml
cat /data/categraf-v0.2.10-linux-amd64/conf/config.toml
[global]
# whether print configs
print_configs = false

# add label(agent_hostname) to series
# "" -> auto detect hostname
# "xx" -> use specified string xx
# "$hostname" -> auto detect hostname
# "$ip" -> auto detect ip
# "$hostname-$ip" -> auto detect hostname and ip to replace the vars
hostname = "$ip"


/ibex/etc/agentd.conf 配置
# debug, release
RunMode = "debug"

# task meta storage dir
MetaDir = "./meta"

[HTTP]
Enable = true
# http listening address
Host = "0.0.0.0"
# http listening port
Port = 2090
# https cert file path
CertFile = ""
# https key file path
KeyFile = ""
# whether print access log
PrintAccessLog = true
# whether enable pprof
PProf = false
# http graceful shutdown timeout, unit: s
ShutdownTimeout = 30
# max content length: 64M
MaxContentLength = 67108864
# http server read timeout, unit: s
ReadTimeout = 20
# http server write timeout, unit: s
WriteTimeout = 40
# http server idle timeout, unit: s
IdleTimeout = 120

[Heartbeat]
# unit: ms
Interval = 1000
# rpc servers
Servers = ["172.18.89.20:20090"]
# $ip or $hostname or specified string
Host = "172.18.89.18"
```

### Relevant logs

```text
none
```

### System info

前端版本：5.9.0 后端版本：v5.10.3-23d7e5a7de5d0ffea7ab941e9621ef7f53071775

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

告警规则报警的时候触发不了自愈脚本。

### Actual behavior

none

### Additional info

none
