### ISSUE TITLE
oidc配置了,没有显示oidc的登陆信息,这是怎么回事啊

### ISSUE THREAD

**Issue by 601579263** [ccfos/nightingale#1197]
### Relevant server.conf | webapi.conf

```toml
[OIDC]
Enable = true
RedirectURL = "http://ip:18000/callback"
SsoAddr = "http://ip/oidc/login"
ClientId = "xxxxxxxxxxxxxx"
ClientSecret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
CoverAttributes = true
# 默认角色
DefaultRoles = ["Standard"]

# 属性映射
[OIDC.Attributes]
Nickname = "nickname"
Phone = "phone_number"
Email = "email"
```

### Relevant logs

```text
oidc配置了,没有显示oidc的登陆信息,这是怎么回事啊
```

### System info

oidc配置了,没有显示oidc的登陆信息,这是怎么回事啊

### Steps to reproduce

1.oidc配置了,没有显示oidc的登陆信息,这是怎么回事啊
2.
3.
...

### Expected behavior

oidc配置了,没有显示oidc的登陆信息,这是怎么回事啊

### Actual behavior

oidc配置了,没有显示oidc的登陆信息,这是怎么回事啊

### Additional info

oidc配置了,没有显示oidc的登陆信息,这是怎么回事啊
