### ISSUE TITLE
oidc配置了，界面提示Failed to fetch

### ISSUE THREAD

**Issue by 601579263** [ccfos/nightingale#1201]
### Relevant server.conf | webapi.conf

```toml
[OIDC]
Enable = true
RedirectURL = "http://夜莺ip:18000/callback"
SsoAddr = "http://我的域名/oidc/login"
ClientId = "xxxxxxxxxxxxxx"
ClientSecret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
CoverAttributes = true
# 默认角色
DefaultRoles = ["Standard"]

# 属性映射
[OIDC.Attributes]
Nickname = "nickname"
Phone = "phone_number"
Email = "email"
```

### Relevant logs

```text
2022/10/17 09:17:01 oidc.go:64: 404 : {"timestamp":1665969433812,"status":404,"error":"Not Found","message":"","path":"/oidc/login/.well-known/openid-configuration"}
```

### System info

oidc配置了，界面提示Failed to fetch

### Steps to reproduce

oidc配置了，界面提示Failed to fetch

### Expected behavior

oidc配置了，界面提示Failed to fetch

### Actual behavior

oidc配置了，界面提示Failed to fetch

### Additional info

![登录界面_副本](https://user-images.githubusercontent.com/24787080/196069653-70ddd05c-f8b4-45ba-b7e4-7915adb5e719.png)
