### ISSUE TITLE
 duplicate key value violates unique constraint  when using pg as database

### ISSUE THREAD

**Issue by JiaLiangC** [ccfos/nightingale#1303]
### Relevant server.conf | webapi.conf

```toml
# debug, release
RunMode = "release"

# # custom i18n dict config
# I18N = "./etc/i18n.json"

# metrics descriptions
MetricsYamlFile = "./etc/metrics.yaml"

BuiltinAlertsDir = "./etc/alerts"
BuiltinDashboardsDir = "./etc/dashboards"

# config | api
ClustersFrom = "config"

# using when ClustersFrom = "api"
ClustersFromAPIs = []

[[NotifyChannels]]
Label = "邮箱"
# do not change Key
Key = "email"

[[NotifyChannels]]
Label = "钉钉机器人"
# do not change Key
Key = "dingtalk"

[[NotifyChannels]]
Label = "企微机器人"
# do not change Key
Key = "wecom"

[[NotifyChannels]]
Label = "飞书机器人"
# do not change Key
Key = "feishu"

[[ContactKeys]]
Label = "Wecom Robot Token"
# do not change Key
Key = "wecom_robot_token"

[[ContactKeys]]
Label = "Dingtalk Robot Token"
# do not change Key
Key = "dingtalk_robot_token"

[[ContactKeys]]
Label = "Feishu Robot Token"
# do not change Key
Key = "feishu_robot_token"

[Log]
# log write dir
Dir = "logs"
# log level: DEBUG INFO WARNING ERROR
Level = "DEBUG"
# stdout, stderr, file
Output = "stdout"
# # rotate by time
# KeepHours: 4
# # rotate by size
# RotateNum = 3
# # unit: MB
# RotateSize = 256

[HTTP]
# http listening address
Host = "0.0.0.0"
# http listening port
Port = 18000
# https cert file path
CertFile = ""
# https key file path
KeyFile = ""
# whether print access log
PrintAccessLog = true
# whether enable pprof
PProf = false
# http graceful shutdown timeout, unit: s
ShutdownTimeout = 30
# max content length: 64M
MaxContentLength = 67108864
# http server read timeout, unit: s
ReadTimeout = 20
# http server write timeout, unit: s
WriteTimeout = 40
# http server idle timeout, unit: s
IdleTimeout = 120

[JWTAuth]
# signing key
SigningKey = "5b94a0fd640fe2765af826acfe42d151"
# unit: min
AccessExpired = 1500
# unit: min
RefreshExpired = 10080
RedisKeyPrefix = "/jwt/"

[BasicAuth]
user001 = "ccc26da7b9aba533cbb263a36c07dcc5"

[AnonymousAccess]
PromQuerier = false
AlertDetail = false

[LDAP]
Enable = false
Host = "ldap.example.org"
Port = 389
BaseDn = "dc=example,dc=org"
# AD: manange@example.org
BindUser = "cn=manager,dc=example,dc=org"
BindPass = "*******"
# openldap format e.g. (&(uid=%s))
# AD format e.g. (&(sAMAccountName=%s))
AuthFilter = "(&(uid=%s))"
CoverAttributes = true
TLS = false
StartTLS = true
# ldap user default roles
DefaultRoles = ["Standard"]

[LDAP.Attributes]
Nickname = "cn"
Phone = "mobile"
Email = "mail"

[OIDC]
Enable = false
RedirectURL = "http://n9e.com/callback"
SsoAddr = "http://sso.example.org"
ClientId = ""
ClientSecret = ""
CoverAttributes = true
DefaultRoles = ["Standard"]

[OIDC.Attributes]
Nickname = "nickname"
Phone = "phone_number"
Email = "email"

[Redis]
# address, ip:port or ip1:port,ip2:port for cluster and sentinel(SentinelAddrs)
Address = "10.202.41.208:26379"
Username = "admin"
Password = "Redis_gdpthreesoctest-123"
# DB = 0
# UseTLS = false
# TLSMinVersion = "1.2"
# standalone cluster sentinel
RedisType = "sentinel"
# Mastername for sentinel type
MasterName = "redis-master"

[DB]
DSN = "host=10.202.41.204 user=nightingale dbname=n9e_v5 password=fkPM0Usc port=5432 sslmode=disable"
# enable debug mode or not
Debug = false
# mysql postgres
DBType = "postgres"
# unit: s
MaxLifetime = 7200
# max open connections
MaxOpenConns = 150
# max idle connections
MaxIdleConns = 50
# table prefix
TablePrefix = ""
# enable auto migrate or not
# EnableAutoMigrate = false
[[Clusters]]
# Prometheus cluster name
Name = "Default"
# Prometheus APIs base url
Prom = "http://gs-server-12236:8428"
# Basic auth username
BasicAuthUser = "vic_admin"
# Basic auth password
BasicAuthPass = "1QAZ2wsx"
# timeout settings, unit: ms
Timeout = 30000
DialTimeout = 3000
MaxIdleConnsPerHost = 100

[Ibex]
Address = "http://127.0.0.1:10090"
# basic auth
BasicAuthUser = "ibex"
BasicAuthPass = "ibex"
# unit: ms
Timeout = 3000
```

### Relevant logs

```text
2022/12/01 10:53:03 ^[[31;1m/home/runner/work/nightingale/nightingale/src/models/common.go:28 ^[[35;1mERROR: duplicate key value violates unique constraint "user_group_pk" (SQLSTATE 23505)
^[[0m^[[33m[1.005ms] ^[[34;1m[rows:0]^[[0m INSERT INTO "user_group" ("name","note","create_at","create_by","update_at","update_by") VALUES
```

### System info

n9e v5.14.2

### Steps to reproduce

1.select pg_terminate_backend(pid) from (select pid from pg_stat_activity where datname = 'n9e_v5' ) a;
2. drop database n9e_v5;
3. create database n9e_v5 owner nightingale;
4.grant all privileges on database n9e_v5 to nightingale;
5.PGPASSWORD=fkPM0Usc psql -h  {pgserverip} -U  nightingale -p 5432 -d n9e_v5 -f /usr/hdp/2.5.0.1-91/nightingale/docker/initsql_for_postgres/a-n9e-for-Postgres.sql

6.create a new business group failed 
ERROR: duplicate key value violates unique constraint "user_group_pk" (SQLSTATE 23505) show in web page

### Expected behavior

after nightingale initialize , could create user group without any problem

### Actual behavior

ERROR: duplicate key value violates unique constraint "user_group_pk" (SQLSTATE 23505)
