### ISSUE TITLE
web界面 单点登陆连接为空

### ISSUE THREAD

**Issue by worker24h** [ccfos/nightingale#1335]
### Relevant server.conf | webapi.conf

```toml
[OIDC]
Enable = true
RedirectURL = "https://a.b.c.d/callback"
SsoAddr = "https://b.c.d.e/auth/realms/"
ClientId = "xxxx"
ClientSecret = "aaaaaa"
CoverAttributes = true
DefaultRoles = ["Standard"]

[OIDC.Attributes]
Openid = "openid"
Nickname = "nickname"
Username = "username"
Phone = "phone_number"
Email = "email"
```

### Relevant logs

```text
空
```

### System info

n9e-v5.14.3-linux-amd64

### Steps to reproduce

![image](https://user-images.githubusercontent.com/24838476/209750460-9ae73deb-b60d-4dcb-964e-7652910684e3.png)

### Expected behavior

空

### Actual behavior

空

### Additional info

单点登陆，在web页面不显示连接
