### ISSUE TITLE
配置了 BuiltinIntegrationsDir 路径以后， icon 显示 404 

### ISSUE THREAD

**Issue by jicki** [ccfos/nightingale#1467]
### Relevant server.conf | webapi.conf

```toml
[Center]
BuiltinIntegrationsDir = "xxx"
```

### Relevant logs

```text
none
```

### System info

v6-ga2

### Steps to reproduce

none

### Expected behavior

正常显示 icon 

### Actual behavior

icon 返回 404

### Additional info

/api/n9e/integrations/icon/xxx 显示均为 404
