### ISSUE TITLE
Deployment of Helm, with three nodes and three collectors, results in only one node visible on the Nightingale platform

### ISSUE THREAD

**Issue by magicmagicspider** [ccfos/nightingale#1730]
### Relevant server.conf | webapi.conf

```toml
[global]
# whether print configs
print_configs = false

# add label(agent_hostname) to series
# "" -> auto detect hostname
# "xx" -> use specified string xx
# "$hostname" -> auto detect hostname
# "$ip" -> auto detect ip
# "$hostname-$ip" -> auto detect hostname and ip to replace the vars
hostname = "$HOSTNAME"

# will not add label(agent_hostname) if true
omit_hostname = false

# s | ms
precision = "ms"

# global collect interval
interval = 15
providers = ["local"]
disable_usage_report = true

[global.labels]
source="categraf"
# region = "shanghai"
# env = "localhost"

[log]
file_name = "stdout"
# max_size is the maximum size in megabytes of the log file before it gets rotated. It defaults to 100 megabytes.
max_size = 100
# max_age is the maximum number of days to retain old log files based on the timestamp encoded in their filename.
max_age = 1
# max_backups is the maximum number of old log files to retain.
max_backups = 1
# local_time determines if the time used for formatting the timestamps in backup files is the computer's local time.
local_time = true
# Compress determines if the rotated log files should be compressed using gzip.
compress = false

[writer_opt]
batch = 1000
chan_size = 1000000

[[writers]]
url = "http://nightingale-center/prometheus/v1/write"

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100

[http]
enable = false
address = ":9100"
print_access = false
run_mode = "release"

# ibex server config
[ibex]
enable = false
## ibex flush interval
interval = "1000ms"
## n9e ibex server rpc address
servers = ["127.0.0.1:20090"]
## temp script dir
meta_dir = "./meta"

[heartbeat]
enable = true

# report os version cpu.util mem.util metadata
url = "http://nightingale-center/v1/n9e/heartbeat"

# interval, unit: s
interval = 10

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

## Optional headers
# headers = ["X-From", "categraf", "X-Xyz", "abc"]

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100
```

### Relevant logs

```text
这是节点pod情况：
[root@master ~]# kubectl get pod -n n9e -o wide
NAME                                  READY   STATUS    RESTARTS   AGE   IP            NODE     NOMINATED NODE   READINESS GATES
nightingale-categraf-v6-ghtjz         1/1     Running   0          26h   10.3.61.41    master   <none>           <none>
nightingale-categraf-v6-n9h6g         1/1     Running   0          26h   10.3.61.42    node     <none>           <none>
nightingale-categraf-v6-pl7c9         1/1     Running   0          26h   10.3.61.43    node2    <none>           <none>
nightingale-center-65d757c976-ms5vb   1/1     Running   3          26h   10.244.2.61   node2    <none>           <none>
nightingale-database-0                1/1     Running   0          25h   10.244.2.62   node2    <none>           <none>
nightingale-nginx-7f5d4545f4-4stbm    1/1     Running   0          26h   10.244.0.68   master   <none>           <none>
nightingale-prometheus-0              1/1     Running   0          25h   10.244.2.63   node2    <none>           <none>
nightingale-redis-0                   1/1     Running   0          25h   10.244.0.69   master   <none>           <none>

[root@master conf]# kubectl exec nightingale-categraf-v6-pl7c9 -it -n n9e -- /bin/bash
root@node2:/# hostname
node2
进入pod后hostname也是正确的
```

### System info

6.0.0

### Steps to reproduce

1.helm部署
2.daemonset三副本
3.数据源选择自带的prometheus
4.查看自带的linux监控
...

### Expected behavior

应该会出现多个节点的监控数据

### Actual behavior

实际三节点，"master,node,node2"只出现了node
![image](https://github.com/ccfos/nightingale/assets/50224719/1f38a0fa-7fe6-4419-a573-9fbbdc4e3045)
