### ISSUE TITLE
https地址探测

### ISSUE THREAD

**Issue by liqiCaic** [ccfos/nightingale#1856]
### Your config.toml

```toml
categraf http_response 模块监控 https 协议的url, 报错 x509: certificate signed by unknown authority

添加 insecure_skip_verify = true 也没有作用

我这里有类似域名的的其他url ,是能正常检测，如何正确配置跳过域名证书检测

配置如下

flashcatcloud/categraf:v0.3.44
[[instances]]
targets = ["https://xx.xx.com/"]
labels = { env="test", instance="test-xx"}
use_tls = true
insecure_skip_verify = true
```

### Relevant logs

```text
categraf http_response 模块监控 https 协议的url, 报错 x509: certificate signed by unknown authority

添加 insecure_skip_verify = true 也没有作用

我这里有类似域名的的其他url ,是能正常检测，如何正确配置跳过域名证书检测

配置如下

flashcatcloud/categraf:v0.3.44
[[instances]]
targets = ["https://xx.xx.com/"]
labels = { env="test", instance="test-xx"}
use_tls = true
insecure_skip_verify = true
```

### System info

centos7.9 categraf0.3.44

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

up

### Actual behavior

我这边做地址，探测的有很多也开启了SKIP跳过证书认证，但是依然没有生效。https的地址有很多依然还是有个别一两个会有报错证书问题，我的本机是可以连接上探测的IP和端口

### Additional info

m
