### ISSUE TITLE
怎么自定义需要采集的nvidia-smi的指标 

### ISSUE THREAD

**Issue by hchgod** [ccfos/nightingale#1920]
### Your config.toml

```toml
# # collect interval
# interval = 15

# exec local command
# e.g. nvidia_smi_command = "nvidia-smi"
nvidia_smi_command = "nvidia-smi"

# exec remote command
# nvidia_smi_command = "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null SSH_USER@SSH_HOST nvidia-smi"

# Comma-separated list of the query fields.
# You can find out possible fields by running `nvidia-smi --help-query-gpus`.
# The value `AUTO` will automatically detect the fields to query.
query_field_names = ""

# query_timeout is used to set the query timeout to avoid the delay of date collection.
query_timeout = "5s"
```

### Relevant logs

```text
暂无
```

### System info

1

### Steps to reproduce

1.
2.
3.
...
暂无

### Expected behavior

自定义nvidia-smi的采集指标

### Actual behavior

暂无
