### ISSUE TITLE
n9e snmp 数据收集失败，后端升级到v7.0.0-beta.4 ,categraf保留v0.3.19 ，指标无法显示

### ISSUE THREAD

**Issue by we104847** [ccfos/nightingale#1960]
### Your config.toml

```toml
[[instances]]
agents = "xxxxxxxx"

timeout = "5s"
version = 2
community = "xxxx"
agent_host_tag = "ident"
retries = 1

[[instances.field]]
oid = "RFC1213-MIB::sysUpTime.0"
name = "uptime"

[[instances.field]]
oid = "RFC1213-MIB::sysName.0"
name = "source"
is_tag = true

[[instances.table]]
oid = "IF-MIB::ifTable"
name = "interface"
inherit_tags = ["source"]

[[instances.table.field]]
oid = "IF-MIB::ifDescr"
name = "ifDescr"
is_tag = true
```

### Relevant logs

```text
后端升级后未向下兼容客户端版本，导致交换机数据无法展示
```

### System info

centos

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

1

### Actual behavior

1
