### ISSUE TITLE
告警自愈、 任务失败

### ISSUE THREAD

**Issue by jicki** [ccfos/nightingale#1979]
### Your config.toml

```toml
[Global]
RunMode = "release"

[Log]
# log write dir
Dir = "logs"
# log level: DEBUG INFO WARNING ERROR
Level = "DEBUG"
# stdout, stderr, file
Output = "stdout"
# # rotate by time
# KeepHours: 4
# # rotate by size
# RotateNum = 3
# # unit: MB
# RotateSize = 256

[HTTP]
# http listening address
Host = "0.0.0.0"
# http listening port
Port = 17000
# https cert file path
CertFile = ""
# https key file path
KeyFile = ""
# whether print access log
PrintAccessLog = false
# whether enable pprof
PProf = true
# expose prometheus /metrics?
ExposeMetrics = true
# http graceful shutdown timeout, unit: s
ShutdownTimeout = 30
# max content length: 64M
MaxContentLength = 67108864
# http server read timeout, unit: s
ReadTimeout = 20
# http server write timeout, unit: s
WriteTimeout = 40
# http server idle timeout, unit: s
IdleTimeout = 120

[HTTP.ShowCaptcha]
Enable = false

[HTTP.APIForAgent]
Enable = true
# [HTTP.APIForAgent.BasicAuth]
# user001 = "ccc26da7b9aba533cbb263a36c07dcc5"

[HTTP.APIForService]
Enable = true
[HTTP.APIForService.BasicAuth]
user001 = "ccc26da7b9aba533cbb263a36c07dcc5"

[HTTP.JWTAuth]
# unit: min
AccessExpired = 1500
# unit: min
RefreshExpired = 10080
RedisKeyPrefix = "/jwt/"

[HTTP.ProxyAuth]
# if proxy auth enabled, jwt auth is disabled
Enable = false
# username key in http proxy header
HeaderUserNameKey = "X-User-Name"
DefaultRoles = ["Developer"]

[HTTP.RSA]
# open RSA
OpenRSA = false

[DB]
# postgres: host=%s port=%s user=%s dbname=%s password=%s sslmode=%s
DSN="root:1234@tcp(mysql:3306)/n9e_v6?charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"
# enable debug mode or not
Debug = false
# mysql postgres
DBType = "mysql"
# unit: s
MaxLifetime = 7200
# max open connections
MaxOpenConns = 150
# max idle connections
MaxIdleConns = 50
# enable auto migrate or not
# EnableAutoMigrate = false

[Redis]
# address, ip:port or ip1:port,ip2:port for cluster and sentinel(SentinelAddrs)
Address = "redis:6379"
# Username = ""
# Password = ""
# DB = 0
# UseTLS = false
# TLSMinVersion = "1.2"
# standalone cluster sentinel
RedisType = "standalone"
# Mastername for sentinel type
# MasterName = "mymaster"
# SentinelUsername = ""
# SentinelPassword = ""

[Alert]
[Alert.Heartbeat]
# auto detect if blank
IP = ""
# unit ms
Interval = 1000
EngineName = "default"

# [Alert.Alerting]
# NotifyConcurrency = 10

[Center]
MetricsYamlFile = "./etc/metrics.yaml"
I18NHeaderKey = "X-Language"
#BuiltinIntegrationsDir = "/app/dashboards/integrations"

[Center.AnonymousAccess]
PromQuerier = true
AlertDetail = true

[Pushgw]
# use target labels in database instead of in series
LabelRewrite = true
# # default busigroup key name
# BusiGroupLabelKey = "busigroup"
ForceUseServerTS = true

# [Pushgw.DebugSample]
# ident = "xx"
# __name__ = "xx"

# [Pushgw.WriterOpt]
# QueueMaxSize = 1000000
# QueuePopSize = 1000

[[Pushgw.Writers]]
Url = "http://victoriametrics:8428/api/v1/write"
# Url = "http://prometheus:9090/api/v1/write"
# Basic auth username
BasicAuthUser = ""
# Basic auth password
BasicAuthPass = ""
# timeout settings, unit: ms
Headers = ["X-From", "n9e"]
Timeout = 10000
DialTimeout = 3000
TLSHandshakeTimeout = 30000
ExpectContinueTimeout = 1000
IdleConnTimeout = 90000
# time duration, unit: ms
KeepAlive = 30000
MaxConnsPerHost = 0
MaxIdleConns = 100
MaxIdleConnsPerHost = 100
## Optional TLS Config
# UseTLS = false
# TLSCA = "/etc/n9e/ca.pem"
# TLSCert = "/etc/n9e/cert.pem"
# TLSKey = "/etc/n9e/key.pem"
# InsecureSkipVerify = false
# [[Pushgw.Writers.WriteRelabels]]
# Action = "replace"
# SourceLabels = ["__address__"]
# Regex = "([^:]+)(?::\\d+)?"
# Replacement = "$1:80"
# TargetLabel = "__address__"

[Ibex]
Enable = true
RPCListen = "0.0.0.0:20090"
```

### Relevant logs

```text
2024-06-04 18:43:58.930808 INFO sender/callback.go:255 task_add_succ: authUser=jicki title=测试脚本 FH: ubuntu
2024-06-04 18:43:59.822231 DEBUG timer/timer_scheduler.go:47 orphan task ids:[2]
2024-06-04 18:43:59.827922 DEBUG timer/timer_scheduler.go:74 task[2] is mine
2024-06-04 18:43:59.827937 DEBUG logic/logic_scheduler.go:12 task[2] scheduling...
2024-06-04 18:43:59.835331 DEBUG logic/logic_scheduler.go:12 task[2] scheduling...
2024-06-04 18:44:00.839055 DEBUG logic/logic_scheduler.go:12 task[2] scheduling...
2024-06-04 18:44:01.440743 INFO memsto/target_cache.go:181 timer: sync targets done, cost: 0ms, number: 3
2024-06-04 18:44:01.479303 DEBUG memsto/host_alert_rule_targets.go:93 get_targets_of_alert_rule total: 0 engine_name:default
2024-06-04 18:44:01.842084 DEBUG logic/logic_scheduler.go:12 task[2] scheduling...
2024-06-04 18:44:01.854632 DEBUG logic/logic_scheduler.go:66 task[2] done
2024-06-04 18:44:04.507561 ERROR ormx/ormx.go:66 /go/pkg/mod/github.com/flashcatcloud/ibex@v1.3.3/src/models/task_action.go:23 record not found
[0.137ms] [rows:0] SELECT * FROM `task_action` WHERE id=2 ORDER BY `task_action`.`id` LIMIT 1
2024-06-04 18:44:05.569056 DEBUG router/router_heartbeat.go:94 heartbeat field:map[] target: {3 1 <nil> ubuntu   [] map[] 1717497836 172.24.0.3  default 1717497835535 26 0 18.64070684315345 8 0.8781099765233724 linux amd64 172.24.0.3}
```

### System info

v6 beta8

### Steps to reproduce
```
1.  创建脚本
2. 执行任务
3. 
```

### Expected behavior

正常执行任务

### Actual behavior

任务失败

![image](https://github.com/ccfos/nightingale/assets/7707585/f871a96e-0a49-45ec-9fb1-2d50b4d7478f)

### Additional info

```bash
mysql> show tables;
+-----------------------+
| Tables_in_n9e_v6      |
+-----------------------+
| alert_aggr_view       |
| alert_cur_event       |
| alert_his_event       |
| alert_mute            |
| alert_rule            |
| alert_subscribe       |
| alerting_engines      |
| audits                |
| board                 |
| board_busigroup       |
| board_payload         |
| builtin_cate          |
| builtin_components    |
| builtin_metrics       |
| builtin_payloads      |
| busi_group            |
| busi_group_member     |
| chart                 |
| chart_group           |
| chart_share           |
| collect               |
| configs               |
| dashboard             |
| datasource            |
| es_index_pattern      |
| event_status          |
| metric_filter         |
| metric_view           |
| notify_tpl            |
| recording_rule        |
| role                  |
| role_operation        |
| sso_config            |
| target                |
| task_action           |
| task_host_0           |
| task_host_1           |
| task_host_10          |
| task_host_11          |
| task_host_12          |
| task_host_13          |
| task_host_14          |
| task_host_15          |
| task_host_16          |
| task_host_17          |
| task_host_18          |
| task_host_19          |
| task_host_2           |
| task_host_20          |
| task_host_21          |
| task_host_22          |
| task_host_23          |
| task_host_24          |
| task_host_25          |
| task_host_26          |
| task_host_27          |
| task_host_28          |
| task_host_29          |
| task_host_3           |
| task_host_30          |
| task_host_31          |
| task_host_32          |
| task_host_33          |
| task_host_34          |
| task_host_35          |
| task_host_36          |
| task_host_37          |
| task_host_38          |
| task_host_39          |
| task_host_4           |
| task_host_40          |
| task_host_41          |
| task_host_42          |
| task_host_43          |
| task_host_44          |
| task_host_45          |
| task_host_46          |
| task_host_47          |
| task_host_48          |
| task_host_49          |
| task_host_5           |
| task_host_50          |
| task_host_51          |
| task_host_52          |
| task_host_53          |
| task_host_54          |
| task_host_55          |
| task_host_56          |
| task_host_57          |
| task_host_58          |
| task_host_59          |
| task_host_6           |
| task_host_60          |
| task_host_61          |
| task_host_62          |
| task_host_63          |
| task_host_64          |
| task_host_65          |
| task_host_66          |
| task_host_67          |
| task_host_68          |
| task_host_69          |
| task_host_7           |
| task_host_70          |
| task_host_71          |
| task_host_72          |
| task_host_73          |
| task_host_74          |
| task_host_75          |
| task_host_76          |
| task_host_77          |
| task_host_78          |
| task_host_79          |
| task_host_8           |
| task_host_80          |
| task_host_81          |
| task_host_82          |
| task_host_83          |
| task_host_84          |
| task_host_85          |
| task_host_86          |
| task_host_87          |
| task_host_88          |
| task_host_89          |
| task_host_9           |
| task_host_90          |
| task_host_91          |
| task_host_92          |
| task_host_93          |
| task_host_94          |
| task_host_95          |
| task_host_96          |
| task_host_97          |
| task_host_98          |
| task_host_99          |
| task_host_doing       |
| task_meta             |
| task_record           |
| task_scheduler        |
| task_scheduler_health |
| task_tpl              |
| task_tpl_host         |
| user_group            |
| user_group_member     |
| users                 |
+-----------------------+
145 rows in set (0.00 sec)

```

```bash
mysql> select * from task_record;
+----+----------+----------+--------------+----------------+----------------+-----------------+---------+-------+-----------+---------+-------+-----------------------------------------------------------------------------------------------------------+------+------------+------------+
| id | event_id | group_id | ibex_address | ibex_auth_user | ibex_auth_pass | title           | account | batch | tolerance | timeout | pause | script                                                                                                    | args | create_at  | create_by  |
+----+----------+----------+--------------+----------------+----------------+-----------------+---------+-------+-----------+---------+-------+-----------------------------------------------------------------------------------------------------------+------+------------+------------+
|  1 |        0 |        1 |              |                |                | ???? FH: ubuntu | root    |     0 |         0 |      30 |       | #!/bin/bash
# e.g.
export PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:~/bin
ss -tln |      | 1717497567 | jicki |
|  2 |        0 |        1 |              |                |                | ???? FH: ubuntu | root    |     0 |         0 |      30 |       | #!/bin/bash
# e.g.
export PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:~/bin
ss -tln |      | 1717497838 | jicki |
+----+----------+----------+--------------+----------------+----------------+-----------------+---------+-------+-----------+---------+-------+-----------------------------------------------------------------------------------------------------------+------+------------+------------+
2 rows in set (0.00 sec)
```
