### ISSUE TITLE
修改JWTAuth过期时间，重启n9e-webapi.service不生效

### ISSUE THREAD

**Issue by xjzyy** [ccfos/nightingale#998]
### Relevant server.conf | webapi.conf

```toml
[JWTAuth]
# signing key
SigningKey = "xxxxxxxxxxxxxxxxxxx"
# unit: min
AccessExpired = 1
# unit: min
RefreshExpired = 1
```

### Relevant logs

```text
systemctl  restart n9e-webapi.service
```

### System info

前端版本：5.5.0 后端版本：5.8.0

### Steps to reproduce

重启不生效

### Expected behavior

1min后点击页面跳转重新登录页面

### Actual behavior

不跳转重新登录页面
